### ISSUE TITLE
bug: Admin 상품 추가하기시, 413 오류 발생

### ISSUE THREAD

**Issue by wonholim** [MJU-TeamProject2/MJU-BE#86]
이미지 크기가 큰 경우 413 오류를 뱉습니다. 제 기억으로는 nginx 문제인거같아요 1MB였나? 이걸 수정하면 사진 크기 때문에 오류가 발생할거같진않습니다. 백엔드 까지 들어가질 않아서 413 오류를 뱉는 경우 프론트에서 따로 핸들링 해주셔야할것같습니다.

**Comment by seongje00416** [comment]
applicatoin.yml 파일 수정 완료
nginx 설정 완료
=> 현재 파일은 최대 10MB로만 업로드 가능하도록 제한 용량을 변경해 해결
